### ISSUE TITLE
`rust-toolchain` is deprecated, use `rust-toolchain.toml` instead

### ISSUE THREAD

**Issue by circuitsacul** [MithicSpirit/lambda-calculus#1]
At least according to github dependabot, it is.

```toml
[toolchain]
channel = "nightly"
```
